### ISSUE TITLE
Not working with Unifi 5.6.10

### ISSUE THREAD

**Issue by Haringstad** [zbx-sadman/unifi_proxy#11]
Great tool, stopped working with Unifi 5.6.10....... 

Could you please look into that? Would be great if it starts working again!!!

Thank you for the superb work!

**Comment by zbx-sadman** [comment]
Hello

What kind of error you have?

**Comment by Haringstad** [comment]
I do not get an error, I do not get any values anymore.....

Just tell me what you would like me to do to provide you info....

Regards,

Jacco van Koll

**Comment by zbx-sadman** [comment]
I have install fresh UniFi Controller v5.6.10 on the Windows, run UniFi Miner (CLI version of Proxy) in debug mode, and got communication error (HTTP status code 500).

Seems that UBNT use TLS 1.2 on default for this release.

I think that you can try one of this ways:

- Uncomment _unifi.https.sslEnabledProtocols=TLSv1,SSLv2Hello_ string in the  _system.properties_ file, which placed into Controller's home dir ("C:\Users\\@username@\Ubiquiti UniFi\data\" on Windows) and restart the controller;
- Change 'tlsv1' to 'TLSv12' string in the _unifi_proxy.pl_ file (see for _IO::Socket::SSL::set_default_context..._ line) and restart the Proxy;

Send to me report, please.

**Comment by Haringstad** [comment]
After making changes:

zabbix_agentd -t "unifi.proxy[discovery,wlan]";
unifi.proxy[discovery,wlan]                   [s|{"data":[]}]


Still no salt ;-)


Running on Raspberry Pi, Raspbian Jessie


Regards,

Jacco van Koll

**Comment by zbx-sadman** [comment]
Okay...

You need to get [UniFi Miner](https://github.com/zbx-sadman/unifi_miner) and run it:  _./unifi_miner.pl -d 3 -c 0 > log.txt_ . Then you can see details of controller's HTTP respose in the log file and locate problem. And you can send the log file to me (email on my github main page).

**Comment by Haringstad** [comment]
That is working, and I do get data. I am now checking if this is caused by
unifi.so (zabbix module), or by unifi_proxy.pl, by using the netcat option.

Regards,

Jacco van Koll

**Comment by zbx-sadman** [comment]
Note that you can enable debug output for Proxy too: _unifi\_proxy.conf -> DebugLevel=3_. If you run it from command line without _-D_ (daemonize) option - messages will be shown on console. One or two requests via _netcat_ will allow to know what is wrong. 

But do not forget about Cache TTL - Proxy can fetch data from local file and you can be confused.

**Comment by Haringstad** [comment]
It is weird, because, unifi_miner.pl DOES colllect proper data, but
unifi_proxy.pl doesn't:

[22701] 2017-07-13 07:01:35 [+] handleConnection() started
[22701] 2017-07-13 07:01:35 [.]  Incoming line: 'discovery,uap'
[22701] 2017-07-13 07:01:35 [+] fetchData() started
[22701] 2017-07-13 07:01:35 [>]  args: object type: 'site'
[22701] 2017-07-13 07:01:35 [.]          Object path: '
https://127.0.0.1:8443/api/self/sites'
[22701] 2017-07-13 07:01:35 [.]          Cache expire or not found. Renew...
[22701] 2017-07-13 07:01:35 [.]          Temporary cache
file='/dev/shm/https___127_0_0_1_8443_api_self_sites.tmp'
[22701] 2017-07-13 07:01:35 [+] fetchDataFromController() started
[22701] 2017-07-13 07:01:35 [>]  args: object path: '
https://127.0.0.1:8443/api/self/sites'
[22701] 2017-07-13 07:01:36 [!] Comminication error: '500 Can't connect to
127.0.0.1:8443'

Regards,

Jacco van Koll

On Thu, Jul 13, 2017 at 12:13 PM, Grigory Prigodin <notifications@github.com

**Comment by Haringstad** [comment]
Em, cannot find your e-mail address ??????

Regards,

Jacco van Koll

**Comment by zbx-sadman** [comment]
Ough, really - no email on page now )) I'll fix it

zbx-sadman@gmail.com

**Comment by Haringstad** [comment]
Stuff is on it's way! Hey, we are all humans, and we all make mistakes!
Most of the time I make them ;-)

Regards,

Jacco van Koll

**Comment by davemuench** [comment]
I ran into the same issue when upgrading my controller from 5.5.11 to 5.5.19, they must of made TLS 1.2 the default somewhere in there. Changing to "tlsv1_2" in unifi_proxy.pl fixed it for me.

Awesome Zabbix integration BTW - thank you!

**Comment by zbx-sadman** [comment]
TLS moved to 1.2 in v1.3.5 release
