### ISSUE TITLE
No data from controller

### ISSUE THREAD

**Issue by CsabiDuke** [zbx-sadman/unifi_proxy#13]
Hello,

I made the unifi.so version of installation, but i have no datas from Unifi Controller:
`# zabbix_agentd -t "unifi.proxy[discovery,wlan]"`
`# unifi.proxy[discovery,wlan]                   [s|{"data":[]}]`

With the unifi_proxy_get script I have the same:
`# ./unifi_proxy_get 127.0.0.1 8448 "discovery,uap"`
`# {"data":[]}`

Unifi Controller Version: 5.5.20
Zabbix Server Version: 3.2.6
Zabbix Agent Version: 3.2.7

What can I do? Am I do something wrong?

Thanking in advance,
CsabiDuke

**Comment by CsabiDuke** [comment]
OMG!
I made a mistake, I changed the 8443 port to 443, for the default https port.
I modified the port in the "unifi_proxy.conf" from 8443 to 443, and it is working now!
`UniFiLocation = https://localhost:443`

Thank you for your work!
CsabiDuke

**Comment by zbx-sadman** [comment]
So good when issue was solved simply ;)
