### ISSUE TITLE
Active check templates use 'Zabbix agent' rather than 'Zabbix agent (active)' for discovery

### ISSUE THREAD

**Issue by rtau-t24** [zbx-sadman/unifi_proxy#14]
Just tried to import templates in https://github.com/zbx-sadman/unifi_proxy/tree/master/Zabbix_Templates/UniFi%20Proxy%201.3.0/UBNT_UniFi_Controller_v_5_Active_Checks and found that the "Discovery rules" are not using the type 'Zabbix agent (active)' but 'Zabbix agent' to query the discovery parameters.

**Comment by zbx-sadman** [comment]
This is a small trick to detect configuration errors: if the data items were created, but nothing came in - that means the user incorrectly configured the Zabbix agent's active mode. In the event that the data items were not created - it incorrectly configured the UniFi Proxy.

**Comment by rtau-t24** [comment]
I see. Would it be better to document the trick to avoid surprise?
________________________________

**Comment by zbx-sadman** [comment]
Okay, i just added this info into Note's - https://github.com/zbx-sadman/unifi_proxy/blob/master/Zabbix_Templates/README.md

Thanks.
