### ISSUE TITLE
Zabbix 3.4 on Debian, Proxy/Agent/netcat setup

### ISSUE THREAD

**Issue by diffway** [zbx-sadman/unifi_proxy#15]
Followed Proxy Guide to configure UniFi proxy v1.3.5 with controller v5.5.20

UniFi Controller has ~50 sites with 1-3 APs each, and about 100 users at per site at peak

```
$ tune unifi_proxy.conf user/password/location
$ mv unifi_proxy.conf /etc/zabbix
$ mv unifi_proxy.pl /usr/local/sbin
$ mv unifi_proxy /etc/init.d/
$ update-rc.d unifi_proxy defaults
$ invoke-rc.d unifi_proxy start
```
After a while, after items started to get values, I noticed that sertain items eventually become unsupported.
The message in Info column displays:
 `Value "" of type "string" is not suitable for value type "Numeric (unsigned)"`
or
 `Value "" of type "string" is not suitable for value type "Float .."`
On next one or two iterations "last check" and value columns updated, then item "recovers".

This effect drifts over items randomly.

In zabbix agent UserParameter conf is

> UserParameter=unifi.proxy[*],echo "$1,$2,$3,$4,$5,$6,$7" |nc 127.0.0.1 8448 -q 1

Testing from shell:
`zabbix_get -s unifi -k unifi.proxy[get,sysinfo,default,version]`
Gives emty string, and after a while it can yeld valid result.

So far no time dependency between queries, apperently cache issue, but can't figure out where. Please Help.

**Comment by zbx-sadman** [comment]
Надеюсь, что по-русски будет понятно, и ответ гонять через гугл-транслятор нет смысла.

Ранее с подобной проблемой ко мне не обращались, поэтому я не совсем понимаю, с какого места начинать анализ.  Нельзя сказать, что нагрузка очень велика - даже в моей маленькой сети  бывало и свыше двухсот одновременно подключенных. Впрочем, кол-во пользователей не должно оказывать большого влияния на производительность, если не производятся в жутких количествах действия, требующие анализа состояния текущих сессий (вычисления RSSI и CCQ и пр.) или данных по всем пользователям, требующим загрузки JSON со "http://unifi/api/...stat/alluser". 

В то же время - я совершенно не знаю, как в реальности ведет себя система в конфигурации с десятками сайтов. Возможно, что есть какая-то проблема с количеством единовременных  сеансов, если так можно выразиться, между UniFi Proxy и UniFi Controller (так как Proxy не закрывает сессию специально для того, чтобы не проходить вновь процесс авторизации при последующих запросах). Либо не хватает ресурсов для открытия TCP сеанса. Так же есть вероятность того, что в каталоге кэша не хватает места и запрошенный JSON не может быть записан. Хотя, полагаю, что в таком случае метрики бы вылетали в ошибочное состояние пачками. Вместе с тем - к UniFi Proxy мой Zabbix agent обращается через loadable module, поэтому в ситуации с _nc_ в качестве посредника у меня банально нет никакой статистики..

И, в конце концов, звёзды сошлись так, что:
1) В Zabbix v3.4 были введены изменения, которые не очень совместимы со скриптами, которые были написаны для ранних версий. У многих пользователей возникли с этим проблемы (не при использовании моего ПО, а вообще);
2) Где-то в v5.5.18 контроллера UniFi в API начали вноситься изменения, метрики стали переименовываться. Возможно, что произошли еще какие-то неафишируемые правки в его (API) работе.
3) В v.1.3.5 UniFi Proxy/UniFi Miner была введена возможность выбирать JSON-backend (или предоставлять выбор автоматическому алгоритму), а он является практически ключевым механизмом скрипта.

Пустая же строка будет выдаваться как при обнаружении в JSON-ключе значения null или "", так и при какой-либо ошибке обработки данных, так любое другое значение может быть ошибочно принято за величину метрики и сбой в работе будет замаскирован.

Поэтому я вынужден констатировать, что хоть какую-то ясность могут внести только отладочные логи или какие-либо приметы, описывающие системность возникающей ошибки. Без этого все мои предположения будут носить точно такой же случайный характер, как и возникающие проблемы.

**Comment by diffway** [comment]
Кхм. Хотелось соблюсти этикет общения в сети - в трансляторе нет необходимости.
Спасибо за быстрый ответ.

**Comment by zbx-sadman** [comment]
Ничего страшного, если будет найдено решение - можно будет оформить его на английском языке. А пока его нет - мне так проще, а вам - понятней.

**Comment by zbx-sadman** [comment]
У меня есть соображение по локализации места возникновения ошибки. Оно, конечно, не очень изящное... Можно сделать некий .sh, в котором будет вызываться в цикле запрос той метрики, которая несет "" в элемент данных. Как только этот запрос вернет пустое значение, сделать мгновенную копию кэша (и лога, если он ведется). Затем уже можно спокойно анализировать файлы кэша на предмет того, что реально получает Proxy на вход и делать какие-либо выводы.

**Comment by diffway** [comment]
По [ссылке](https://disk.yandex.ru/d/Db-np422jcfLAA) есть немного пищи для размышлений..

Конфига агента принципиально не изменилась:
> UserParameter=unifi.proxy[*],echo "$1,$2,$3,$4,$5,$6,$7" |nc 127.0.0.1 8443 -q 1

Чтобы избежать буферизации запускал демона командой [script](https://unix.stackexchange.com/questions/25372/turn-off-buffering-in-pipe/25378#answer-61833)

Лог получен командой:
`
$ script -q /var/log/unifi-proxy.debug.timer -c '/usr/local/sbin/unifi_proxy.pl -C /etc/zabbix/unifi_proxy.conf' 2>&1 > /var/log/unifi-proxy.debug.log
`

Между командами в терминале пауза 5-10 сек.

Комит: [a2b7f76](https://github.com/zbx-sadman/unifi_proxy/commit/a2b7f76868756caa9ac9bb880f9d8cfa7a56d798)

В скрипте `unifi_proxy.pl` менял:
>MAX_BUFFER_LEN => 131072

В конфиге менял:

> CacheMaxAge = 30
> UniFiVersion = v5
> DebugLevel = 3
> StartServers = 8
> MaxClients = 60
> ListenPort = 8443

Что-то нужно повторить/изменить/любые вопросы - спрашивайте.

**UPD**: 
- Файлы кеша имеют стабильный размер и содержат запрашиваемые данные, поэтому в архив я их не включил.
- Порядок команд в вызове `script` перепутан, но _AFAIK_ суть не меняется.
- С StartServers = 1 ситуация аналогична.

**Comment by zbx-sadman** [comment]
Логи я ваши скачал, но вам их лучше удалить - там присутствует излишняя информация.
Однако я там ничего не обнаружил криминального...  "sysinfo,default,version" присутствует в JSON, из метрики значение возвращается. Пустого значения в логах нет. Или я чего-то не увидел?

**Comment by diffway** [comment]
_Факт 1_: Через дробное количество периодов опроса скрипт возвращает пустую строку, что вынуждает _zabbix_ поставить флаг _NOT_SUPPORTED_ на соответствующий _элемент данных_
Уменьшение периода _refresh unsupported items_ этой проблемы не решает, а лишь увеличивает нагрузку на контроллер и на сам _zabbix_.
_Факт 2_: То что в логах действительно нет ничего "криминального" сбивает с толку. Возможно потеря данных происходит где-то ещё в цепочке.

Нужно отметить что _[unif_miner](https://github.com/zbx-sadman/unifi_miner)_ отдаёт данные стабильно.

PS: В фичу третьего _zabbix_, _[preprocessing](https://www.zabbix.com/documentation/3.4/manual/appendix/items/preprocessing)_, была [добавлена](https://www.zabbix.com/documentation/3.4/manual/introduction/whatsnew340?s[]=jsonpath#new_preprocessing_options) возможность парсить json, что существено разгружает _zabbix_, плюс за счёт _[зависимых элементов данных](https://www.zabbix.com/documentation/3.4/manual/introduction/whatsnew340?s[]=dependent#bulk_metrics_and_dependent_items)_ даёт необходимую для формирования вычисляемых метрик "консистентность" данных.

**Comment by zbx-sadman** [comment]
Могу наугад тыкнуть в параметр _MaxRequestsPerChild_ конфига Proxy. Через это количество запросов форк пересоздается, хотя, конечно, при этом всё должно корректно закрываться, иначе бы у меня тоже всё вылетало в NOT_SUPPORTED. Увеличьте его радикально... Код Proxy идентичен коду Miner, различие только в том, что Proxy принимает команды через TCP-соединение несколькими форками.

Если не поможет, то нужно смотреть на живой системе, заочно у меня диагноз ставить не выходит.

Про препроцессинг я знаю. Вещь интересная, но, насколько я понял, выборки с ее помощью на данный момент делать нельзя. Т.е. вы не сможете отобрать значение метрики с ключом _type_, которая относится к объекту JSON с заданным значением ключа _id_. А уж сложить _users_num_ со всех объектов с _type="UAP"_ и подавно.

P.S. Закрыл issue случайно.

**Comment by diffway** [comment]
Насколько я могу судить увеличение _MaxRequestsPerChild_ не решит проблемы, а лишь отсрочит её проявление.

Поясню про препроцессинг..

Для zabbix 3.4 

Cоздаём _item_ с _value_type_ "текст"

Любым доступным способом доставляем json содержащий нужные метрики объекта (прописывается соответствующий нашему способу _item type_)

Далее создаём новый _item_, задаём ему тип _dependent_, а в его препроцессинг _JsonPath_ вписываем например "_$.stat.rx_bytes_". 

Т.к значения зависимых метрик заполняются сразу после обновления своего мастера, по крайней мере, для соответствующего _id_, _rx_bytes_ будет соответствовать _tx_bytes_.

Вычисления различных сумм можно делать из файла кеша.

**Comment by zbx-sadman** [comment]
Увеличение не решит, но, возможно, своей отсрочкой укажет, где начать искать ошибку.

За разъяснения спасибо, но у меня нет ресурсов сопровождать все доступные для всех выпусков Zabbix способы доставки значений. К тому же выигрыш в производительности для Proxy будет мизерным - основная работа алгоритма состоит в том, чтобы найти этот самый кусок JSON, содержащий нужную метрику. А отправить ее в TCP-сессию  - дело пары операторов. Если же пользоваться loadable module, то выигрыш будет стремиться к нулю при увеличении сложности поддержки всего этого добра.

Если вам нужно персональное решение - можем это обсудить.

**Comment by zbx-sadman** [comment]
Накидал на коленке отдачу куска JSON в 1.3.6. Пока только в Miner. С Zabbix не тестировал (нет инсталляции 3.4), но вроде как JSON отдает правильный: https://github.com/zbx-sadman/unifi_miner/tree/master/experimental

Отдельные девайсы/вложенные объекты JSON отбираются с помощью фильтра, берется только первый подходящий под условие объект, например:  
```./unifi_miner.pl -a raw -o uap -s default -k "[mac=00:27:22:0a:16:a7].*"```

Подключ '*' в действии _raw_ завершает анализ дерева, в других - игнорируется.

Если погоняете и все будет работать, то внесу тот же код в Proxy.
