### ISSUE TITLE
Zabbix agent 3.2.10 gives: Got signal [signal:11(SIGSEGV),reason:1,refaddr:(nil)]. Crashing ...

### ISSUE THREAD

**Issue by sbjcom** [zbx-sadman/unifi_proxy#20]
We have your current unifi proxy running for many months with the Zabbix Agent 3.2.7. But today we updated the Zabbix Agent via their repository on an Oracle Linux 7.3 server and it gave us the error:

Got signal [signal:11(SIGSEGV),reason:1,refaddr:(nil)]. Crashing ...

I rebuilt the unifi.so file from zabbix source 3.2.10 and deployed it, all based on your instructions, but the same error occurred. We had to return to using a 3.2.7 agent to restore functionality.

The agent produced additional output, which i have attached.
[unifi_proxy_errors.txt](https://github.com/zbx-sadman/unifi_proxy/files/1576589/unifi_proxy_errors.txt)

**Comment by zbx-sadman** [comment]
Hello
It looks like issue #18. 
If you used old loadable module sources - just download updated code and compile it again.

**Comment by sbjcom** [comment]
Thank you. I downloaded the updated module code and it is now working with the latest agent. This issue is resolved.

Side comment ... because the version number had not changed, I assumed that all of the code was all current.

**Comment by zbx-sadman** [comment]
Yes, module does not have any version. In the begin i didn't plan to rewrite it.
