### ISSUE TITLE
List of available proxy commands

### ISSUE THREAD

**Issue by tobiasehlert** [zbx-sadman/unifi_proxy#21]
Hi,

Is there some list of which type of commands I can run to get data from my Unifi proxy?

And in this case I mean, what I can insert in here (marked in bold):
./unifi_proxy_get 127.0.0.1 8448   "**discovery,uap**"

Regards,
Tobias

**Comment by zbx-sadman** [comment]
Hello Tobias

UniFi Proxy use the same mechanics that UniFi Miner. All commands and options are equal. You need to feed utility with string as following: _[action],[object_type],[sitename],[key],[id or mac],[null_replacer],[cache_max_age]_ 

Refer to "Command Line Options" section in https://github.com/zbx-sadman/unifi_miner/wiki/UniFi-Miner-guide-in-English. For example, to _action_ field you can place _get_, to _object\_type_ - _site_, to sitename - your sitename, to _key_ -  _\_id_ . Resulting query string is: "get,site,default,_id".

**Comment by tobiasehlert** [comment]
Hi Grigory,

Thanks for your reply, but I was more curious in how to determine, what I can run. Is it possible to list all available commands in the proxy web interface maybe?

Regards,
Tobias

**Comment by zbx-sadman** [comment]
Tobias, 

What you mean under "commands" - whole query string or _action_ field values list?
In the query string only two field have the final number of options: _action_ (get, max, discovery, etc.) and _object_type_ (uap, site, user and etc). Their admissible values are listed in the UniFi Miner's guide.

All other options in query string is UniFi Controller depended values (some of its can exist in v5.6, or in v4 only or available for all releases). No vendor provided list exists, i taked all from API answer.

Unfortunately. Proxy have no web interface and i have no plan to create it.
