### ISSUE TITLE
Zabbix Template: Special characters are not allowed in the parameters.

### ISSUE THREAD

**Issue by eroji** [zbx-sadman/unifi_proxy#23]
After setting up unifi_proxy and configuring Zabbix with the passive check templates, a good amount of the items are showing up as "Not Supported" with reason as "Special characters "\, ', ", `, *, ?, [, ], {, }, ~, $, !, &, ;, (, ), <, >, |, #, @, 0x0a" are not allowed in the parameters." I am not sure clear on why this is happening. It is able to retrieve the other items just fine. The conf is set to use v5 and the Controller is running on 5.6.29. Items that are not working for instance:

Automatic upgrade firmware
UAP "Upstairs" clients with excellent signal
UAP "Upstairs" clients with low signal

**Comment by eroji** [comment]
Looks like this is an issue with the zabbix-agent limiting the character set allowed for UserParameters. Override was available in the conf and now it's working.

**Comment by tiagoIW** [comment]
@eroji I have the same problem with zabbix agent 3.4 What changes did you make in zabbix conf to adjust ?

**Comment by zbx-sadman** [comment]
Just add ``UnsafeUserParameters=1`` to the agent's config and restart service.
