### ISSUE TITLE
Unable to associate template

### ISSUE THREAD

**Issue by mmerlone** [zbx-sadman/unifi_proxy#28]
Hi,
Trying to monitor half dozen UAP, software controller V5.8, Ubuntu 18.04 server both on unifi controller and zabbix server.
`zabbix_agentd -t unifi.proxy[discovery,uap]` works on command line, but when I try to associate a template with a UAP host I get this message:

> Cannot find host interface on "apu-fab.domain.tld" for item key "unifi.proxy[discovery,uap]".

Thanks for your assistance and time to make this code, best regards. Let me know if you need further information.

**Comment by mmerlone** [comment]
Oops. Never mind. I just realized I have to associate the template with the controller host, not the UAP host.

**Comment by zbx-sadman** [comment]
OK. Seems that no help need
