### ISSUE TITLE
compilation inifi.so

### ISSUE THREAD

**Issue by hznovich** [zbx-sadman/unifi_proxy#3]
Доброго времени суток. Помогите решить проблему. При компиляции inifi.so в консоль вываливается ошибка:
gcc -fPIC -shared -o unifi.so unifi.c -I ../../../include
unifi.c:1:20: fatal error: sysinc.h: No such file or directory
 #include "sysinc.h"
                    ^
compilation terminated.
make: **\* [unifi] Error 1

Ubuntu 14.04. gcc, make установлены

**Comment by zbx-sadman** [comment]
Всё делали по шагам, как тут написано? 
[Wiki](https://github.com/zbx-sadman/unifi_proxy/wiki/UniFi-Proxy-Guide-in-Russian) - > Интеграция с системой мониторинга Zabbix

**Comment by hznovich** [comment]
Извиняюсь за не внимательность. Все получилось.
