### ISSUE TITLE
Zabbix Server does not get data

### ISSUE THREAD

**Issue by amosfolz** [zbx-sadman/unifi_proxy#30]
Hello,

Can you please check my configuration? I have been struggling to get Unifi_Proxy to work for many hours now. I can run the test command in documentation and get a response OK: 
![image](https://user-images.githubusercontent.com/33728190/57389281-d20b7280-7187-11e9-894e-fd8e8c0cb149.png)

Then on my Zabbix Server I have created a new host and applied the templates you provided:
![image](https://user-images.githubusercontent.com/33728190/57389260-c7e97400-7187-11e9-91a2-5004ad751316.png)

But no data is ever gathered, only "Unifi System Info":
![image](https://user-images.githubusercontent.com/33728190/57389415-21ea3980-7188-11e9-98a3-b7777ec59574.png)

**Comment by zbx-sadman** [comment]
Hello Amos

Seems like Zabbix's active check feature setup is not complete. See ServerActive option in the agent's config file or just use ["Passive_Checks" templates](https://github.com/zbx-sadman/unifi_proxy/tree/master/Zabbix_Templates/UniFi%20Proxy%201.3.0/UBNT_UniFi_Controller_v_5_Passive_Checks)

**Comment by amosfolz** [comment]
Thanks for the suggestion. I do have `ServerActive` and `Hostname` values set in my `zabbix_agentd.conf` file. 

Any other ideas?

**Comment by amosfolz** [comment]
Sadman, 

Thanks for the pointers. With your help I was able to determine I had the wrong configuration. 
I checked error log at `var/log/zabbix/zabbix_agent.log` and noticed the below error message:
```
  4427:20190508:160207.282 sending [{"request":"active checks","host":"SRV6"}]
  4427:20190508:160207.282 before read
  4427:20190508:160207.284 got [{"response":"failed","info":"host [SRV6] not found"}]
```

This is due to me being new to Zabbix, but I thought the config `Hostname` value should equal DNS server hostname. This is incorrect. Here is a summary in case it helps someone in the future. 

![image](https://user-images.githubusercontent.com/33728190/57406015-d0ed3c00-71ad-11e9-8a91-4042f9897b8c.png)

**Comment by zbx-sadman** [comment]
Amos, all right now. 

"Host interface" field's DNS Name used to make passive checks only (via DNS resolving). 
You can use "Visible name" field and "assign" human-readable name to host.

Please close issue if no problem still there and good luck with UniFi works in the Marion city.
