### ISSUE TITLE
unifi_proxy return only 25AP's

### ISSUE THREAD

**Issue by romoromor** [zbx-sadman/unifi_proxy#34]
Hi,

i have Unifi Controller with more than 150 AP's.
When i'm using unifi_miner, all is ok (only performance is bad).
For better performance, i want to use unifi_proxy.
I deploy it to server. Proxy is working, but when i execute for example main discovery query
/usr/local/bin/zabbix/unifi_proxy_get 127.0.0.1 8448
i get only 25 AP's.
Why? Where could be a problem?

**Comment by zbx-sadman** [comment]
Hello

Unfortunately, i have only six UAPs and can't reproduce this case on my own system.
