### ISSUE TITLE
Incorrect max columns provided for screen element

### ISSUE THREAD

**Issue by yaroz** [zbx-sadman/unifi_proxy#35]
Hello.  I am trying to import the templates into a new load of Zabbix 4.4, and getting "Incorrect max columns provided for screen element" on the controller, uap, and user active templates.  The usw template imported just fine.  I've attempted to change/delete the max columns in the xml, but that did not work.

**Comment by yaroz** [comment]
I removed the screens section out of the UAP xml and it imported fine.  I then went in and re-added the screens per the original xml, and everything is good.  I just did a comparison of the newly exported file and the one from here, and I don't see anything other than placement of the resource.  All of the other elements are the same for the screens.

**Comment by zbx-sadman** [comment]
Hello

Unfortunately, i have Zabbix 4.2 installation only, and can't reproduce this case.

**Comment by c-10001001** [comment]
Can confirm that this also occurs on my zabbix 4.4 install.
Might even be broken in Zabbix code since I can manually create the screens as described however when I export that template with screens I can no longer import it.
