### ISSUE TITLE
Cant import templates

### ISSUE THREAD

**Issue by blanosko** [zbx-sadman/unifi_proxy#37]
Hi I have a little problem where I cant import any template besides USW one (active and passive). Other templates throw error at importing:

![Capture](https://user-images.githubusercontent.com/26611576/82880512-d21b1380-9f3e-11ea-93bd-00ff83441471.PNG)

I cant find any info on this issue.

**Zabbix 5.0, Ubuntu Server 20.0.4 (Focal)**

Thanks for response.

**Comment by nicology36** [comment]
I had the same problem. Just uncheck "Template screens" and import of the template should work.
