### ISSUE TITLE
*** stack smashing detected ***

### ISSUE THREAD

**Issue by hznovich** [zbx-sadman/unifi_proxy#4]
Здравствуй. Направь пожалуйста на правильный путь. Библиотеку скомпилировал, все положил и прописал как в инструкции. Но если ввести zabbix_agentd -t "unifi.proxy[discovery,wlan]" в консоли получаю следующее: 

```
[60067] 2016-07-11 10:20:24 [-] addToLLD() finished
[60067] 2016-07-11 10:20:24 [.] Make LLD JSON
*** stack smashing detected ***: zabbix_agentd terminated
unifi.proxy[discovery,wlan]                  [60067] 2016-07-11 10:20:24 [-] handleConnection() finished
Aborted (core dumped)
```

После этого zabbix агент умирает. В чем может быть проблема?

**Comment by zbx-sadman** [comment]
Не могу сказать, что являюсь большим специалистом в написании загружаемых модулей под Zabbix, чтобы сходу определить причину, но, по крайней мере, мне было бы неплохо узнать о среде запуска (какая OS, какая версия Zabbix-server/agent, насколько большой (в килобайтах) список должен быть получен по _[discovery,wlan]_ ). А так же о работе Zabbix agent в тех же условиях, но без использования загружаемого модуля, например - с UserParameter + netcat или UserParameter + [unifi_proxy_get.c](https://raw.githubusercontent.com/zbx-sadman/unifi_proxy/master/src/unifi_proxy_get.c)

На данный момент могу сказать, что использую Zabbix v 2.4.x под Debian 7 и ни разу так у меня агент не падал.
