### ISSUE TITLE
cannot parse as a valid JSON object: unexpected end of string data

### ISSUE THREAD

**Issue by knpshkn** [zbx-sadman/unifi_proxy#40]
Добрый день,
При использовании Unifi-Proxy версии 1.3.8 (JsonOutput=pretty) у нас возникла проблема с интеграцией UniFi Virtual Access Points discovery.
В заббиксе это выражено сообщением "Invalid discovery rule value: cannot parse as a valid JSON object: unexpected end of string data".
При попытке выполнить запрос вручную на сервере мы видим, что происходит не полный вывод json. В нем явно не все объекты и нет закрывающих скобок.
Пример окончания вывода
```
{
         "{#UAPMAC}" : "f0:9f:c2:30:cd:2c",
         "{#ID}" : "5e7d538ca9f6163bb0c3c9c9",
```

Немного о инсталляции:
Контроллеры с 7-10 сайтами, от 1 до 30 точек доступа в каждом сайте.

**Comment by zbx-sadman** [comment]
Автоматическое отсекание может произойти, если общая длина результирующей JSON-строки (ответа Zabbix-серверу) > 65535 байт. 
Это было связано с ограничениями в старых версиях Zabbix и UniFi Proxy. Сейчас, полагаю, те проблемы неактуальны, поэтому можно подправить (увеличить) переменную `MAX_BUFFER_LEN` в `unifi_proxy.pl`

**Comment by knpshkn** [comment]
@zbx-sadman я пробовал указывать "MAX_BUFFER_LEN => 131072" но ситуация не изменилась. Попробую еще раз. Если есть рекомендации по числу, напишите пожалуйста.

**Comment by zbx-sadman** [comment]
Никаких особых рекомендаций нет.  В принципе - я больше не могу навскидку вспомнить место в коде, где ещё могло бы происходить усечение. 

Если ничего не найдёте, можете выслать мне кэш UniFi Proxy - при возможности я посмотрю что происходит на ваших, реальных данных.

**Comment by knpshkn** [comment]
@zbx-sadman сейчас проверил еще раз, установлен "MAX_BUFFER_LEN => 131072", такая же ситуация. Нужен какой то определенный файл из кэша или все пачкой?
Я проверяю так:
`./unifi_proxy_get 127.0.0.1 8448 "discovery,uap,,vap_table"`
в кэшэ есть такие файлы - https://pastebin.com/RBA8pbJX

**Comment by zbx-sadman** [comment]
`vap_table`, по-моему, формируется из `https___localhost_8443_api_s_XXXXXXX_stat_device`, но на 100% не уверен

**Comment by knpshkn** [comment]
del

**Comment by zbx-sadman** [comment]
Проверил на UniFi Miner. 
Конкретно с этим файлом я не вижу проблем:
```
{
   "data" : [
      {
         "{#UAPMAC}" : "f0:9f:c2:2c:38:8f",
         "{#ESSID}" : "guest",
         "{#UP}" : "1",
         "{#STATE}" : "RUN",
         "{#SITEDESC}" : "xi576s7n",
         "{#UAPNAME}" : "ORL-01",
         "{#SITENAME}" : "xi576s7n",
         "{#UAPID}" : "5e943a4ba9f6167b55e1ebf0",
         "{#ID}" : "5e942d1aa9f6167b55e1eaa3"
      },
...
      {
         "{#UAPMAC}" : "fc:ec:da:8c:f9:0c",
         "{#ESSID}" : "guest",
         "{#UP}" : "1",
         "{#STATE}" : "RUN",
         "{#SITEDESC}" : "xi576s7n",
         "{#UAPNAME}" : "TAM-01",
         "{#SITENAME}" : "xi576s7n",
         "{#UAPID}" : "5ea25c99a9f6167b55ea6f9c",
         "{#ID}" : "5e942d1aa9f6167b55e1eaa3"
      }
   ]
}
```

**Comment by knpshkn** [comment]
Спасибо. Проверил на втором сервере, такая же картина.

**Comment by zbx-sadman** [comment]
Тогда надо дебажить на целевой системе или на полном наборе данных из кэша. Иных вариантов не вижу.

**Comment by knpshkn** [comment]
Думаю я понял в чем проблема. В unifi_proxy_get.c так же имеется [параметр ](https://github.com/zbx-sadman/unifi_proxy/blob/cde37543f3a68460bc143f0ba80bd2e4e4733586/src/unifi_proxy_get.c#L7) `#define MAX_BUFFER_LEN    65535` увеличил его как и в самом перл файле, скомпилировал unifi_proxy_get по новой, вроде полет нормальный.
