### ISSUE TITLE
Template for zabbix 2.0

### ISSUE THREAD

**Issue by Pimmetje** [zbx-sadman/unifi_proxy#5]
Currently there is a template for Zabbix 2.4 is there also one that works for 2.0 or 2.2?

**Comment by zbx-sadman** [comment]
You can adopt the template manually - it's not so complex.

Zabbix v2.4 export the LLD filter as array of structs, but pre v2.4 use oly one XML-tag to save/restore the LLD filter.

So, i think that replacements inside of the _template.xml_ file (for several times) maded before import can be enough:

```
<filter>
<evaltype>0</evaltype>
<formula/>
<conditions/>
</filter>

```

to

`<filter>:</filter>`

...and i remember that v2.2 (or v2.0) uses for trigger's condition  _&_ signs instead _and_ word. But i does not seem to have used...

**Comment by Pimmetje** [comment]
I also had to remove the screens. But it did import. Thanks.

Another small question i used: 
UserParameter=unifi.proxy[*],/usr/local/bin/unifi_miner.pl -a "$1" -o "$2" -s "$3" -k "$4" -i "$5" -n "$6" -c "$7
But how does it get the username and password?
If i do :
/usr/local/bin/unifi_miner.pl
I get 
{"data":[]}

If i add -u username -p password i get output. 

So i added username and password in this config is this correct?

**Comment by zbx-sadman** [comment]
Two ways is exists:

1) Change Miner's command line: `UserParameter=unifi.proxy[*],/usr/local/bin/unifi_miner.pl -a "$1" -o "$2" -s "$3" -k "$4" -i "$5" -n "$6" -c "$7  -u "your_username" -p "your_password"`;
2) Change default settings inside _unifi_miner.pl_ - search `'unifiuser' => ['u', TYPE_STRING, 'stat']` and  `'unifipass'  => ['p', TYPE_STRING, 'stat']` , then replace stat/stat to your_username/your_password.

So, if you want. then you can send to me adopted template for sharing to all via GitHub. My e-mail address placed on main page of profile.

**Comment by Pimmetje** [comment]
I opted for option 1. 
With zabbix agent (active) it does not want to work some how. If i change them to Zabbix Agent they work. As we have a proxy this is not a issue. (Only i can't bulk edit a discovery rule. So ill change the template for that i think). 
Pinging the AP is only possible when the zabbix server and the AP are on the same network. So those i disabled. 
Ill let u know how the progress is going (BTW ill use the beta version of the miner all others gave null as output).
Edit: 
I didn't had the active check enabled on the zabbix agent. Lets see what it does.

**Comment by zbx-sadman** [comment]
Hmm... what is "beta-version"? I haven't beta for 4 months at least.

"AP ping" items works when Zabbix Server can ping AP's network using routing.

But you can make your own _unifi.ping[{#IP}]_ item prototype like that:
`UserParameter=unifi.ping[*], ping -c 1 $1 >/dev/null 2>&1 && echo 1 || echo 0`

**Comment by Pimmetje** [comment]
The problem with the AP here is there on remote sites. So unless unifi can ping them or i have a proxy on site there is no way that would work. 
Also i found i had to add the {$FW_UAP_LATEST_VER} macro

I mean 1.3.4 (Experimental)

**Comment by zbx-sadman** [comment]
_experimental/unifi_miner.pl_ and _/unifi_miner.pl_ - these two files are identical to each other. I just forget to delete .pl from _experimental/_ dir after release.

On remote sites you can use 'ping'-item, that defined via UserParameter. But you can analyze UAP state (_unifi.proxy[get,uap,{#SITENAME},state,{#ID}]_) too. See prototype description for more information.

**Comment by Pimmetje** [comment]
I still have some issues with some items (haven't looked at it yet)
unifi.proxy[pcount,user,tqcut91p,"[ap_mac=80:2a:a8:xx:xx:xx].[rssi>15&rssi<=25].rssi",,0]
I get 
Special characters "\, ', ", `, *, ?, [, ], {, }, ~, $, !, &, ;, (, ), <, >, |, #, @, 0x0a" are not allowed in the parameters

**Comment by zbx-sadman** [comment]
Its Zabbix security feature has explained in [Zabbix agent unsafe user parameters issue](https://github.com/zbx-sadman/unifi_proxy/issues/1) and [Miner's guide](https://github.com/zbx-sadman/unifi_miner/wiki/UniFi-Miner-guide-in-English):

_Zabbix's data item going to UNSUPPORTED state_

_Symptom: complex keys, which contains the filter causes data item going to UNSUPPORTED state._
_Possible reason: the Zabbix agent cannot process the key containing the characters'[', '&', ']' and etc._
_Fix: use the UnsafeUserParameters=1 directive in the Zabbix-agent configuration file._
