### ISSUE TITLE
Template gives no data elements.

### ISSUE THREAD

**Issue by belykhk** [zbx-sadman/unifi_proxy#7]
Hello, i installed unifi_proxy on my zabbix server.

Then i import template to my zabbix, i noticed that there is 11 groups of data elements and 11 data element (i suppose there must be more). 

Zabbix - 3.2.1

**Comment by zbx-sadman** [comment]
So.. 
Do u see any values in Zabbix's Latest data?
Do you turn on Active mode on Zabbix Agent?

**Comment by belykhk** [comment]
After some time (like 2 hours) lastest data started to show, but it has really big latency (like 10min between checks on UniFi Access Points (1395 data elements)). Is there any way to increase speed of update or decrease number of items for each AP monitored?
unifi_proxy settings:

```
MaxClients=100
StartServers=8
MaxRequestsPerChild=2048
CacheMaxAge=200
```

**Comment by zbx-sadman** [comment]
UniFi Proxy/Miner have no slowdown features implemented.

You can control _CacheMaxAge_ option only. The script compare request processing start time and the cache file creation time. If the time is different more than _CacheMaxAge_ (sec) - actual data is fetched from the UniFi controller and the cache file is recreated. You can clean _CacheDir_ and wait for little time.  Then you will see new cache files.  Or you can just do _ls_ from time to time to see changing of the cache file creation time.

Update interval for the _UniFi Access Points discovery rule_ (see Zabbix's LLD feature) is 10min. If you adopt the new UAP - its will be found in 0...10 minutes. But all "old" UAP's metrics stay polled with max latency in _CacheMaxAge+Item update interval_  sec.

The number of active Zabbix data items te can be reduced by turning off _Item prototypes_ in the _UniFi Access Points discovery_ rule that contained in the _Template UBNT UniFi Controller_.

Also, i think that _StartServers=8_ is so much. Every Proxy instance is required ~50-60mb of RAM (yes, it's Perl ;). One Server thread can serve ~1000 req/sec (if CPU is fast enought.)

**Comment by belykhk** [comment]
Well, RAM Usage is not very big problem for me :)
I'll play with some settings and if i can manage to work zabbix properly, i will sent a reply! Thanks for help!
